import 'package:flutter/material.dart';
final Color primaryColor = const Color(0xff102e30);
final Color darkColor = const Color(0xff075e54);
final Color secondaryColor = const Color(0xff00897b);
final Color highlightColor = const Color(0xff357c74);
final Color scaffoldBgColor = const Color(0xfffafafa);
final Color fabBgColor = const Color(0xff20c659);
final Color fabBgSecondaryColor = const Color(0xff507578);
final Color lightGrey = const Color(0xffe2e8ea);
final Color profileDialogBgColor = const Color(0xff73bfb8);
final Color profileDialogIconColor = const Color(0xff8ac9c3);
final Color chatDetailScaffoldBgColor = const Color(0xffe7e2db);
final Color iconColor = const Color(0xff858b90);
final Color textFieldHintColor = const Color(0xffcdcdcd);
final Color messageBubbleColor = const Color(0xffe1ffc7);
final Color blueChecColor = const Color(0xff3fbbec);
final Color statusThumbnailBorderColor = const Color(0xff21bfa6);
final Color notificationBadgeColor = const Color(0xff08d160);